spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    application:
      data-center-id: 3
      worker-id: 5
  jackson:
    default-property-inclusion: non_null
mybatis:
  configuration:
    map-underscore-to-camel-case: true